import LocalizedStrings from 'react-localization';

export const strings = new LocalizedStrings({
    en: {
        cookiesPolicy: "Cookies policy",
        heading1: "WHAT ARE COOKIES?",
        cookie1: "Cookies are tiny text files stored on your computer every time you visit certain web pages. We use cookies to keep track of the car you are booking and to remember you when you return to our site.",
        cookie2: "To book a car on our website, you need to have cookies enabled – see the section on Managing cookies. If you do not wish to enable cookies you will still be able to browse the site and use it for research purposes. Most web browsers have cookies enabled, but check Managing Cookies for help to turn them on should you need to.",
        cookie3: "Please be aware that cookies cannot harm your computer. We do not store personally identifiable information such as credit card details in cookies we create, but we do use encrypted information gathered from them to help improve the user’s experience of the site. For example, they help us to identify and resolve errors.",
        cookie4: "We’re providing you with this information as part of our initiative to comply with recent legislation and to ensure that we’re honest and clear about your privacy when using our website.",
        heading2: "OUR COOKIES POLICY",
        heading3: "INFORMATION ABOUT OUR USE OF COOKIES",
        cookie5: "Our website uses cookies to distinguish you from other users of our website. This helps us to provide you with a good experience when you browse our website and also allows us to improve our site.",
        cookie6: "A cookie is a small file of letters and numbers that we store on your browser or the hard drive of your computer if you agree. Cookies contain information that is transferred to your computer's hard drive.",
        cookie7: "Here’s a list of the main cookies that we use, and what we use them for. You’ll find information about third party cookies on the next tab.",
        cookie8: "Except for essential cookies, all cookies will expire after 30 days.",
        tableHeading1: "Cookie Name",
        tableHeading2: "Looks Like",
        tableHeading3: "Cookie Purpose",
        tableHeading4: "Type",
        tableInfo1: "Booking Cookie",
        tableInfo2: "CT:IE269164250, CT:IE269167130, CT:IE269169530, CT:US269189450, CT:US269190770, CT:US269191010, CT:US269192730, CT:US269204450, CT:US269205970, CT:US269208490, CT:US269208690, CT:US269209090, CT:PT269933370, CT:IE269936050, CT:IE269939250, CT:IE269939650, CT:IE269940130, CT:US271363810, CT:US271364250",
        tableInfo3: "Shows where a booking has been made",
        tableInfo4: "Strictly Necessary",
        tableInfo5: "Live Chat",
        tableInfo6: "__livechat, mp_ca50c6970591e306292637c2d7565daf_mixpanel __utmc, kvcd, __utma, km_uq, km_ai, km_lv LiveChat_13178052558062703",
        tableInfo7: "Allows users to instant message a customer service agent",
        tableInfo8: "Functional",
        tableInfo9: "Client Identification",
        tableInfo10: "clientCookie",
        tableInfo11: "Used for maintaining correct clientId across sections",
        tableInfo12: "Strictly Necessary",
        tableInfo13: "Session Identifier",
        tableInfo14: "7ktc6skvbat8dl0ddolggh5ij4",
        tableInfo15: "Identifies sessions across sections",
        tableInfo16: null,
        tableInfo17: "Abandonment Email",
        tableInfo18: "email_id",
        tableInfo19: "Necessary for abandonment email. Identifies when customers visit the site and leave without making a booking.",
        tableInfo20: "Functional",
        tableInfo21: "Omniture",
        tableInfo22: "s_vi, s_campaign, s_ppv, s_sq, s_cc",
        tableInfo23: "Omniture – signifies omniture tracking",
        tableInfo24: "Performance",
        tableInfo25: "Google Analytics",
        tableInfo26: "__utmz, __utmx, __utmxx, __utmc",
        tableInfo27: "Allows Google to perform tracking on the website",
        tableInfo28: "Performance",
        heading4: "THIRD PARTY COOKIES",
        cookie9: "When you visit Cabforce you may notice some cookies that are not related to Cabforce. When you visit a page that contains embedded content, for example from YouTube, you may be sent cookies from these websites. We don't control the setting of these cookies, so we suggest you check the third-party websites for more information about their cookies and how to manage them.",
        cookie10: "Some of the third party cookies we use are 'analytical' cookies. They allow us to recognise and count the number of visitors and to see how visitors move around the site when they are using it. This helps us to improve the way our website works, for example, by ensuring that users are finding what they are looking for easily. You can find more information about the individual cookies we use and the purposes for which we use them in the table below:",
        cookie11: "Third party cookies in relation targeted advertising are also set when you visit our website. Please see Banner Advertising tab for further details",
        tableInfo29: "Trade Doubler",
        tableInfo30: "01716ca8622704ae607bb75720039166",
        tableInfo31: "Identifies users as having arrived from Trade Doubler Advert",
        tableInfo32: "Performance",
        cookie12: "You block cookies by activating the setting on your browser that allows you to refuse the setting of all or some cookies. However, if you use your browser settings to block all cookies (including essential cookies) you may not be able to access all or parts of our site.",
        heading5: "MANAGING COOKIES",
        cookie13: "If you have not enabled cookies on your browser it will mean that the shopping experience on your browser will be limited to browsing and researching, you will not be able to purchase goods.",
        heading6: "To enable cookies",
        cookie14: "If you're unsure about the type and version of web browser you use to access the Internet:",
        boldText1: "For PCs: ",
        cookie15: "click on 'Help' at the top of your browser window and select the 'About' option ",
        boldText2: "For Macs: ",
        cookie16: "with the browser window open, click on the Apple menu and select the 'About' option",
        heading7: "How to check cookies are enabled for PCs",
        GoogleChrome: "Google Chrome",
        bullet1: "Click on 'Tools' at the top of your browser window and then click Options",
        bullet2: "Click the 'Under the Hood' tab, locate the 'Privacy' section, and click the 'Content settings' button",
        bullet3: "Now select 'Allow local data to be set'",
        IE: "Microsoft Internet Explorer 6.0, 7.0, 8.0",
        bullet4: "Click on 'Tools' at the top of your browser window and click 'Internet options' , then click on the 'Privacy' tab",
        bullet5: "Ensure that your Privacy level is set to Medium or below, which will enable cookies in your browser",
        bullet6: "Settings above Medium will disable cookies",
        Mozilla: "Mozilla Firefox",
        bullet7: "Click on 'Tools' at the top of your browser window and select Options",
        bullet8: "Then click the Privacy icon",
        bullet9: "Click on Cookies, then select 'allow sites to set cookies'",
        Safari: "Safari",
        bullet10: "Click on the Cog icon at the top of your browser window and select the 'Preferences' option",
        bullet11: "Click on 'Security', check the option that says 'Block third-party and advertising cookies'",
        bullet12: "Click 'Save'",
        Opera: "Opera",
        bullet13: "Click on 'Menu' at the top of your browser window and select 'Settings'",
        bullet14: "Then select 'Preferences', select the 'Advanced' tab",
        bullet15: "Then select 'Accept cookies' option",
        SafariOsx: "Safari on OSX",
        bullet16: "Click on 'Safari' at the top of your browser window and select the 'Preferences' option",
        bullet17: "Click on 'Security' then 'Accept cookies'",
        bullet18: "Select the 'Only from site you navigate to'",
        heading8: "All other browsers",
        cookie17: "Please check your documentation or your online help files.",
        heading9: "Further information about cookies",
        cookie18: "If you'd like to learn more about cookies in general and how to manage them, visit",
        link: " www.aboutcookies.org",
        cookie185: "(opens in a new window - please note that we can't be responsible for the content of external websites).",
        heading10: "BANNER ADVERTISING ON OTHER WEBSITES",
        cookie19: "The purpose of this type of advertising is to provide you with a range of products based on what you’re viewing on our website, which are presented to you when you visit other selected websites. The adverts may highlight offers deemed relevant to your browsing history. The technology behind some of these adverts is based on cookies.",
        cookie20: "Learn more about cookies and why we use them via the ‘What are cookies’ tab.",
        heading11: "YOUR PRIVACY",
        cookie21: "Please be assured that the data contained in the cookies used in these adverts is completely anonymous and does not contain any of your personal details."
    },

    fr: {
        cookiesPolicy: "Politique en matière de cookies",
        heading1: "QUE SONT LES COOKIES ?",
        cookie1: "Les cookies sont de petits fichiers texte stockés sur votre ordinateur à chaque fois que vous visitez certaines pages web. Nous utilisons des cookies pour identifier la voiture que vous réservez et pour nous souvenir de vous lorsque vous revenez visiter notre site.",
        cookie2: "Pour réserver une voiture sur notre site internet, vous devez avoir activé les cookies : voir la section Gestion des cookies. Si vous ne souhaitez pas activer les cookies, vous aurez toujours la possibilité de naviguer sur notre site et d'effectuer des recherches. La plupart des navigateurs internet ont activé les cookies, mais reportez-vous à la section Gestion des cookies pour savoir comment les activer le cas échéant.",
        cookie3: "Veuillez noter que les cookies ne peuvent pas endommager votre ordinateur. Nous ne stockons pas de données d'identification personnelle dans les cookies que nous créons, mais nous utilisons des informations cryptées collectées à partir de ces cookies pour nous permettre d'améliorer l'expérience des utilisateurs du site. Ils nous aident, par exemple, à identifier et résoudre les erreurs.",
        cookie4: "La communication de cette information fait partie de notre initiative visant à nous conformer à la récente législation et à vous assurer de notre honnêteté et transparence concernant le respect de votre vie privée lorsque vous naviguez sur notre site.",
        heading2: "NOTRE POLITIQUE EN MATIÈRE DE COOKIES",
        heading3: "INFORMATIONS CONCERNANT NOTRE UTILISATION DES COOKIES",
        cookie5: "Notre site internet utilise les cookies pour vous différencier des autres utilisateurs de notre site internet. Cela nous permet de vous proposer une expérience de navigation agréable et d'améliorer notre site.",
        cookie6: "Un cookie est un petit fichier contenant des chiffres et des lettres que nous stockons sur votre navigateur ou le disque dur de votre ordinateur si vous l'acceptez. Les cookies contiennent des informations qui sont transférées sur le disque dur de votre ordinateur.",
        cookie7: "Voici une liste des principaux cookies que nous utilisons et de leur utilisation. Vous trouverez des informations sur les cookies tierce partie dans l'onglet suivant.",
        cookie8: "À part les cookies essentiels, tous les cookies ont une date d'expiration de 30 jours.",
        tableHeading1: "Nom du cookie",
        tableHeading2: "Ressemble à",
        tableHeading3: "Fonction du cookie",
        tableHeading4: "Type",
        tableInfo1: "Cookie de réservation",
        tableInfo2: "",
        tableInfo3: "Montre où une réservation a été effectuée",
        tableInfo4: "Strictement nécessaire",
        tableInfo5: "Chat en ligne",
        tableInfo6: "__livechat, mp_ca50c6970591e306292637c2d7565daf_mixpanel __utmc, kvcd, __utma, km_uq, km_ai, km_lv LiveChat_13178052558062703",
        tableInfo7: "Permet aux utilisateurs d'envoyer des messages instantanés avec un agent du service clientèle",
        tableInfo8: "Fonctionnel",
        tableInfo9: "Identification du client",
        tableInfo10: "clientCookie",
        tableInfo11: "Utilisé pour conserver une identification correcte du client entre les sections",
        tableInfo12: "Strictement nécessaire",
        tableInfo13: "Identifiant de session",
        tableInfo14: "7ktc6skvbat8dl0ddolggh5ij4",
        tableInfo15: "Identifie les sessions entre les sections",
        tableInfo16: null,
        tableInfo17: "E-mail d'abandon",
        tableInfo18: "email_id",
        tableInfo19: "Nécessaire pour l'envoi d'un e-mail d'abandon. Identifie lorsque le client quitte le site visité sans avoir fait de réservation.",
        tableInfo20: "Fonctionnel",
        tableInfo21: "Omniture",
        tableInfo22: "s_vi, s_campaign, s_ppv, s_sq, s_cc",
        tableInfo23: "Omniture – indique un suivi par Omniture",
        tableInfo24: "Performance",
        tableInfo25: "Google Analytics",
        tableInfo26: "_utmz, __utmx, __utmxx, __utmc",
        tableInfo27: "Permet à Google de faire un suivi sur le site",
        tableInfo28: "Performance",
        heading4: "COOKIES TIERCE PARTIE",
        cookie9: "Lorsque vous visitez Cabforce, vous pouvez remarquer certains cookies qui sont ne pas liés à Cabforce. Lorsque vous visitez une page qui contient du contenu intégré, provenant par exemple de YouTube, vous pouvez recevoir des cookies de ces sites internet. Nous ne contrôlons pas le paramétrage de ces cookies, nous vous conseillons donc de vérifier les sites internet de ces tierces parties concernant leurs cookies et la manière dont ils les gèrent.",
        cookie10: "Certains des cookies tierce partie sont des cookies « analytiques ». Ils nous permettent de connaître et de compter le nombre de visiteurs et de voir comment les visiteurs se comportent sur le site lorsqu'ils l'utilisent. Cela nous aide à améliorer la façon dont notre site internet fonctionne, par exemple, en nous assurant que les utilisateurs trouvent facilement les informations qu'ils recherchent. Vous pouvez trouver plus d'informations concernent les cookies individuels que nous utilisons et la fonction de ces cookies dans le tableau ci-dessous :",
        cookie11: "Les cookies tierce partie liés à la publicité ciblée sont également stockés lorsque vous visitez notre site internet. Reportez-vous à la section Bannières publicitaires pour plus d'informations",
        tableInfo29: "Trade Doubler",
        tableInfo30: "01716ca8622704ae607bb75720039166",
        tableInfo31: "Identifie les utilisateurs provenant de Trade Doubler Advert",
        tableInfo32: "Performance",
        cookie12: "Vous bloquez les cookies en activant le paramètre de votre navigateur qui vous permet de refuser le stockage de la totalité ou d'une partie des cookies. Toutefois, si vous utilisez les paramètres de votre navigateur pour bloquer la totalité des cookies (y compris les cookies strictement nécessaires), vous pourriez ne pas pouvoir accéder à toutes les parties de notre site internet.",
        heading5: "GESTION DES COOKIES",
        cookie13: "Si vous n'avez pas activé les cookies sur votre navigateur, cela signifie que votre expérience d'achat en ligne sera limitée à la navigation et la recherche et que vous ne pourrez acheter aucun produit ou service.",
        heading6: "Activation des cookies",
        cookie14: "Si vous ne connaissez pas le type et la version du navigateur que vous utilisez pour accéder à internet :",
        boldText1: "Pour les PCs:",
        cookie15: "cliquez sur « Aide » en haut de votre fenêtre de navigation puis sélectionnez « À propos de »",
        boldText2: "Pour les Macs:",
        cookie16: "une fois la fenêtre de votre navigateur ouverte, cliquez sur le menu Pomme puis sélectionnez « À propos de",
        heading7: "Comment vérifier si les cookies sont activés pour les PC",
        GoogleChrome: "Google Chrome",
        bullet1: "Cliquez sur « Outils » en haut de votre fenêtre de navigation puis cliquez sur « Options »",
        bullet2: "Cliquez sur l'onglet « Options avancées » et cliquez sur le bouton « Paramètres de contenu »",
        bullet3: "	Maintenant sélectionnez « Autoriser le stockage des données locales »",
        IE: "Microsoft Internet Explorer 6.0, 7.0, 8.0",
        bullet4: "Cliquez sur « Outils » en haut de votre fenêtre de navigation puis cliquez sur « Options internet » et ensuite cliquez sur l'onglet « Confidentialité »",
        bullet5: "Assurez-vous que votre niveau de Confidentialité est fixé à « Moyenne » ou à un niveau inférieur, ce qui activera les cookies pour votre navigateur",
        bullet6: "Les niveaux supérieurs à « Moyenne » désactiveront les cookies",
        Mozilla: "Mozilla Firefox",
        bullet7: "Cliquez sur « Outils » en haut de votre fenêtre de navigation puis sélectionnez « Options »",
        bullet8: "Ensuite cliquez sur l'icône Vie privée",
        bullet9: "Dans la section Pistage, sélectionnez « Indiquer aux sites que je souhaite être pisté »",
        Safari: "Safari",
        bullet10: "Cliquez sur l'icône représentant une roue dentée en haut de votre fenêtre de navigation et sélectionnez « Préférences »",
        bullet11: "Cliquez sur « Confidentialité » et cochez l'option qui indique « Bloquer les cookies des tierces parties et des annonceurs »",
        bullet12: "Cliquez sur Enregistrer",
        Opera: "Opera",
        bullet13: "Cliquez sur « Menu » en haut de votre fenêtre de navigation puis sélectionnez « Réglages »",
        bullet14: "Ensuite sélectionnez « Vie privée et sécurité » puis la section « Cookies »",
        bullet15: "Enfin sélectionnez l'option « Permettre la création de données locales »",
        SafariOsx: "Safari on OSX",
        bullet16: "Cliquez sur « Safari » en haut de votre fenêtre de navigation puis sélectionnez l'option « Préférences »",
        bullet17: "Cliquez sur « Confidentialité » et cochez l'option qui indique « Bloquer les cookies des tierces parties et des annonceurs »",
        bullet18: "Sélectionnez « Uniquement des sites que je visite »",
        heading8: "Tous les autres navigateurs",
        cookie17: "Reportez-vous à la documentation disponible ou à l'aide en ligne.",
        heading9: "Informations complémentaires concernant les cookies",
        cookie18: "Si vous souhaitez obtenir plus d'informations sur les cookies en général et sur la manière de les gérer, visitez le site",
        link: "www.aboutcookies.org ",
        cookie185: "(ouvre une nouvelle fenêtre – veuillez noter que nous ne sommes pas responsables du contenu de sites externes).",
        heading10: "BANNIÈRES PUBLICITAIRES SUR D'AUTRES SITES",
        cookie19: "L'objectif de ce type de publicités est de vous proposer une large gamme de produits en fonction de ce que vous regardez sur notre site internet. Ces publicités sont affichées à votre attention lorsque vous visiter certains autres sites internet. Elles peuvent mettre en avant des offres pouvant vous intéresser en fonction de votre historique de navigation. La technologie derrière ce type de publicités est basée sur les cookies.",
        cookie20: "Pour en savoir plus sur les cookies et pourquoi nous les utilisons, consultez l'onglet « Que sont les cookies ».",
        heading11: "RESPECT DE LA VIE PRIVÉE",
        cookie21: "Soyez assuré que les données contenues dans les cookies utilisés par ces publicités sont totalement anonymes et ne contiennent aucune information personnelle."
    },

    es: {
        cookiesPolicy: "Política de cookies",
        heading1: "¿QUÉ SON LAS COOKIES?",
        cookie1: "Las cookies son pequeños archivos de texto que se almacenan en su ordenador cada vez que visita determinadas páginas web. Utilizamos cookies para hacer un seguimiento del coche que está reservando y para reconocerle cuando vuelva a entrar en nuestro sitio.",
        cookie2: "Para reservar un coche en nuestro sitio web, necesitará tener habilitadas las cookies. Consulte el apartado «Administración de cookies». Si no quiere habilitar las cookies, podrá navegar de todas formas por el sitio y utilizarlo para realizar búsquedas. La mayoría de los navegadores web tienen habilitadas las cookies, pero le recomendamos consultar el apartado «Administración de cookies» para obtener ayuda sobre cómo activarlas si es preciso.",
        cookie3: "Tenga en cuenta que las cookies no pueden dañar su ordenador. No almacenamos información identificable a título personal como datos de tarjetas de crédito en las cookies que creamos, pero utilizamos información encriptada recopilada con ellas para mejorar la experiencia de navegación de los usuarios de nuestro sitio. Por ejemplo, nos ayudan a identificar y resolver errores.",
        cookie4: "Le damos esta información dentro de nuestra iniciativa para cumplir con la legislación reciente y para garantizar nuestra honestidad y transparencia en relación con la confidencialidad durante el uso de nuestro sitio web.",
        heading2: "NUESTRAS NORMAS SOBRE COOKIES",
        heading3: "INFORMACIÓN ACERCA DEL USO QUE HACEMOS DE LAS COOKIES",
        cookie5: "Nuestro sitio web utiliza cookies para distinguirle de otros usuarios del mismo. Esto nos ayuda a ofrecerle una experiencia satisfactoria cuando navegue por nuestro sitio y nos permite, además, mejorarlo.",
        cookie6: "Una cookie es un pequeño archivo de letras y números que almacenamos en su navegador o el disco duro de su ordenador si usted nos lo permite. Las cookies contienen información que se transfiere al disco duro de su ordenador.",
        cookie7: "A continuación encontrará una lista de las principales cookies que empleamos y una explicación de para qué las utilizamos. Encontrará información acerca de las cookies de terceros en la siguiente pestaña.",
        cookie8: "Excepto las cookies esenciales, todas las demás expiran al cabo de 30 días.",
        tableHeading1: "Nombre de la cookie",
        tableHeading2: "Aspecto",
        tableHeading3: "Finalidad",
        tableHeading4: "Tipo",
        tableInfo1: "Cookie de reserva",
        tableInfo2: "",
        tableInfo3: "Muestra dónde se ha realizado una reserva",
        tableInfo4: "Imprescindible",
        tableInfo5: "Chat en vivo",
        tableInfo6: "__livechat, mp_ca50c6970591e306292637c2d7565daf_mixpanel __utmc, kvcd, __utma, km_uq, km_ai, km_lv LiveChat_13178052558062703",
        tableInfo7: "Permite a los usuarios utilizar el servicio de mensajería instantánea con un agente de atención al cliente",
        tableInfo8: "Funcional",
        tableInfo9: "Identificación del cliente",
        tableInfo10: "clientCookie",
        tableInfo11: "Se utiliza para mantener la ID de cliente correcta en las diferentes secciones",
        tableInfo12: "Imprescindible",
        tableInfo13: "Identificador de sesión",
        tableInfo14: "7ktc6skvbat8dl0ddolggh5ij4",
        tableInfo15: "Identifica las sesiones en las diferentes secciones",
        tableInfo16: null,
        tableInfo17: "E-mail de abandono",
        tableInfo18: "email_id",
        tableInfo19: "Necesaria para los e-mail de abandono. Identifica cuándo los clientes visitan el sitio y lo abandonan sin hacer una reserva.",
        tableInfo20: "Funcional",
        tableInfo21: "Omniture",
        tableInfo22: "s_vi, s_campaign, s_ppv, s_sq, s_cc",
        tableInfo23: "Omniture (es decir, seguimiento Omniture)",
        tableInfo24: "Rendimiento",
        tableInfo25: "Google Analytics",
        tableInfo26: "__utmz, __utmx, __utmxx, __utmc",
        tableInfo27: "Permite que Google realice un seguimiento del sitio web",
        tableInfo28: "Rendimiento",
        heading4: "COOKIES DE TERCEROS",
        cookie9: "Cuando visite Cabforce, puede que vea algunas cookies que no están relacionadas con Cabforce. Cuando visite una página que contenga contenido incrustado, por ejemplo, desde YouTube, puede que esos sitios web le envíen cookies. No podemos controlar la configuración de esas cookies, por lo que le sugerimos que compruebe los sitios web de esos terceros para obtener más información acerca de sus cookies y cómo las administran.",
        cookie10: "Algunas de las cookies de terceros que empleamos son cookies «analíticas». Nos permiten reconocer y contar el número de visitantes y ver cómo se mueven estos por nuestro sitio cuando lo están utilizando. Esto nos ayuda a mejorar el funcionamiento de nuestro sitio web al asegurarnos de que los usuarios encuentren fácilmente lo que están buscando. Encontrará más información acerca de las cookies individuales que utilizamos y para qué fines las empleamos en la tabla que sigue:",
        cookie11: "Cuando visite nuestro sitio web también se le enviarán cookies de terceros en relación con publicidad personalizada. Consulte la pestaña «Banners publicitarios» para obtener más información",
        tableInfo29: "Trade Doubler",
        tableInfo30: "01716ca8622704ae607bb75720039166",
        tableInfo31: "dentifica a los usuarios que han llegado desde Trade Doubler Advert",
        tableInfo32: "Rendimiento",
        cookie12: "Puede bloquear las cookies activando la opción de su navegador que le permite rechazar el almacenamiento de la totalidad o parte de las cookies. Sin embargo, si configura su navegador para bloquear todas las cookies (incluidas las imprescindibles), puede que no le resulte posible acceder a la totalidad o parte de nuestro sitio.",
        heading5: "ADMINISTRACIÓN DE COOKIES",
        cookie13: "Si no ha habilitado las cookies en su navegador, esto hará que la experiencia de compra se vea limitada a navegar y buscar, ya que no podrá realizar compras.",
        heading6: "Cómo activar las cookies",
        cookie14: "Si no está seguro del tipo y versión del navegador que utiliza para acceder a Internet:",
        boldText1: "Para PCs:",
        cookie15: "haga clic en «Ayuda» en la parte superior de su ventana de navegación y seleccione la opción «Acerca de»",
        boldText2: "Para Macs:",
        cookie16: "con la ventana de navegación abierta, haga clic en el menú «Apple» y seleccione la opción «Acerca de»",
        heading7: "Cómo comprobar si las cookies están habilitadas en un PC",
        GoogleChrome: "Google Chrome",
        bullet1: "Haga clic en «Herramientas» en la parte superior de su ventana de navegación y luego en «Configuración»",
        bullet2: "Haga clic en la pestaña «Mostrar opciones avanzadas», localice la sección «Privacidad» y haga clic en el botón «Configuración de contenido»",
        bullet3: "Seleccione «Permitir que se almacenen datos locales",
        IE: "Microsoft Internet Explorer 6.0, 7.0, 8.0",
        bullet4: "Haga clic en «Herramientas» en la parte superior de su ventana de navegación; luego, haga clic en «Opciones de Internet» y, finalmente, en la pestaña «Privacidad»",
        bullet5: "Asegúrese de que su configuración de privacidad sea «Media» o «Baja», lo que habilitará las cookies en su navegador",
        bullet6: "Las configuraciones superiores a «Media» deshabilitan las cookies",
        Mozilla: "Mozilla Firefox",
        bullet7: "Haga clic en «Herramientas» en la parte superior de su ventana de navegación y seleccione «Opciones»",
        bullet8: "Luego, haga clic en el icono «Privacidad»",
        bullet9: "Haga clic en «Cookies» y seleccione «Aceptar cookies de las web»",
        Safari: "Safari",
        bullet10: "Haga clic en el icono de la rueda en la parte superior de su navegador y seleccione la opción «Preferencias»",
        bullet11: "Haga clic en «Seguridad» y marque la opción «Bloquear cookies de publicidad y terceros»",
        bullet12: "Haga clic en «Guardar»",
        Opera: "Opera",
        bullet13: "Haga clic en «Menú» en la parte superior de su ventana de navegación y seleccione «Configuración»",
        bullet14: "Seleccione luego «Opciones» y vaya a la pestaña «Avanzado»",
        bullet15: "Seleccione luego la opción «Aceptar cookies»",
        SafariOsx: "Safari en OSX",
        bullet16: "Haga clic en «Safari» en la parte superior de su ventana de navegación y seleccione la opción «Preferencias»",
        bullet17: "Haga clic en «Seguridad» y seleccione «Aceptar cookies»",
        bullet18: "Seleccione la opción «Solo de los sitios a los que navegue»",
        heading8: "Todos los demás navegadores",
        cookie17: "Compruebe su documentación o los archivos de ayuda en línea.",
        heading9: "Más información acerca de las cookies",
        cookie18: "Si desea obtener más información acerca de las cookies en general o cómo administrarlas, visite",
        link: "www.aboutcookies.org",
        cookie185: "(se abrirá una nueva ventana; tenga en cuenta que no nos hacemos responsables del contenido de los sitios web externos).",
        heading10: "BANNERS PUBLICITARIOS EN OTROS SITIOS WEB",
        cookie19: "La finalidad de este tipo de publicidad es ofrecerle una selección de productos basada en lo que está viendo en nuestro sitio web, que se le presentará cuando visite otros sitios web seleccionados. La publicidad puede destacar ofertas consideradas relevantes de acuerdo con su historial de navegación. La tecnología subyacente a algunos de esos anuncios se basa en cookies.",
        cookie20: "Puede obtener más información acerca de las cookies y por qué las empleamos en la pestaña «Qué son las cookies».",
        heading11: "SU PRIVACIDAD",
        cookie21: "Puede tener la seguridad de que los datos incluidos en las cookies utilizadas en esos anuncios son totalmente anónimos y no contienen ningún dato personal suyo."
    },

    dt: {
        cookiesPolicy: "Cookie-Richtlinien",
        heading1: "WAS SIND COOKIES?",
        cookie1: "Cookies sind winzige Textdateien, die jedes Mal, wenn Sie bestimmte Internetseiten besuchen, auf Ihrem Computer gespeichert werden. Wir verwenden Cookies, um Ihre Mietwagenbuchung zu verfolgen und Sie zu identifizieren, wenn Sie wieder unsere Seite besuchen.",
        cookie2: "Um ein Auto auf unserer Internetseite zu buchen, müssen Sie die Cookies aktiviert haben – siehe Abschnitt über die Verwaltung der Cookies. Wenn Sie die Cookies nicht aktivieren möchten, können Sie trotzdem auf der Seite surfen und sie zur Recherche verwenden. Bei den meisten Internetbrowsern sind Cookies aktiviert, aber lesen Sie „Verwaltung der Cookies”, um sie gegebenenfalls aktivieren zu können.",
        cookie3: "Bitte denken Sie daran, dass Cookies Ihren Rechner nicht schädigen können. Wir speichern mit unseren Cookies keine personenbezogenen identifizierbaren Informationen wie Kreditkartendaten, aber wir verwenden die verschlüsselten Informationen, die wir von Ihnen erhalten, um die Benutzererfahrung auf der Seite zu verbessern. Sie helfen uns zum Beispiel dabei, Fehler zu identifizieren und zu beseitigen.",
        cookie4: "Wir bieten Ihnen diese Informationen im Rahmen unserer Bemühungen, der neuen Gesetzgebung zu entsprechen, und um Ihnen zu versichern, dass wir ehrlich und transparent mit Ihren persönlichen Daten umgehen, wenn Sie unsere Internetseite besuchen.",
        heading2: "UNSERE COOKIE-RICHTLINIEN",
        heading3: "INFORMATIONEN ÜBER UNSERE VERWENDUNG VON COOKIES",
        cookie5: "Unsere Internetseite verwendet Cookies, um Sie von anderen Benutzern unserer Internetseite zu unterscheiden. Dies hilft uns dabei, unsere Internetseite und Ihre Benutzererfahrung beim Besuch unserer Seite zu verbessern.",
        cookie6: "Ein Cookie ist eine kleine Datei mit Buchstaben und Zahlen, die wir bei Ihrer Zustimmung in Ihrem Browser oder auf der Festplatte Ihres Computers speichern. Cookies enthalten Daten, die auf die Festplatte Ihres Computers übertragen werden.",
        cookie7: "Im Folgenden sehen Sie eine Liste der wichtigsten von uns benutzten Cookies und wofür wir sie verwenden. Sie finden Informationen zu Cookies von Dritten im nächsten Register.",
        cookie8: "Mit Ausnahme der grundlegenden Cookies werden alle Cookies nach 30 Tagen gelöscht.",
        tableHeading1: "Cookie-Bezeichnung",
        tableHeading2: "Aussehen",
        tableHeading3: "Zweck des Cookies",
        tableHeading4: "Art",
        tableInfo1: "Buchungs-Cookie",
        tableInfo2: "",
        tableInfo3: "Zeigt, wo eine Buchung durchgeführt wurde",
        tableInfo4: "Unbedingt notwendig",
        tableInfo5: "Live Chat",
        tableInfo6: "__livechat, mp_ca50c6970591e306292637c2d7565daf_mixpanel__utmc, kvcd, __utma, km_uq, km_ai, km_lv LiveChat_13178052558062703",
        tableInfo7: "Ermöglicht dem Benutzer Instant Messages zu einem Kundenbetreuer zu senden",
        tableInfo8: "Funktional",
        tableInfo9: "Kundenidentifizierung",
        tableInfo10: "clientCookie",
        tableInfo11: "Wird verwendet, um bereichsübergreifend die korrekte Kunden-ID zu erhalten",
        tableInfo12: "Unbedingt notwendig",
        tableInfo13: "Sitzungs-ID",
        tableInfo14: "7ktc6skvbat8dl0ddolggh5ij4",
        tableInfo15: "Identifiziert bereichsübergreifend Sitzungen",
        tableInfo16: null,
        tableInfo17: "Verzichts-E-Mail",
        tableInfo18: "email_id",
        tableInfo19: "Notwendig für Verzichts-E-Mails. Identifiziert Besuche von Kunden auf der Internetseite ohne Buchung.",
        tableInfo20: "Funktional",
        tableInfo21: "Omniture",
        tableInfo22: "s_vi, s_campaign, s_ppv, s_sq, s_cc",
        tableInfo23: "Omniture – bezeichnet Omniture-Tracking",
        tableInfo24: "eistung",
        tableInfo25: "Google Analytics",
        tableInfo26: "__utmz, __utmx, __utmxx, __utmc",
        tableInfo27: "Ermöglicht Google ein Tracking auf der Internetseite",
        tableInfo28: "Leistung",
        heading4: "COOKIES VON DRITTEN",
        cookie9: "Wenn Sie Cabforce besuchen, bemerken Sie vielleicht, dass einige Cookies nicht mit Cabforce in Verbindung stehen. Wenn Sie eine Seite mit eingebetteten Inhalten besuchen, zum Beispiel von YouTube, können Sie von diesen Internetseiten Cookies erhalten. Wir kontrollieren nicht den Einsatz dieser Cookies, deshalb empfehlen wir Ihnen, auf den Internetseiten Dritter nach weiteren Informationen zu deren Cookies und ihrer Verwaltung zu suchen.",
        cookie10: "Einige der Cookies von Dritten verwenden wir als „analytische” Cookies. Sie erlauben uns, Kunden zu erkennen und die Kundenanzahl zu bestimmen, und sie informieren uns darüber, wie sich Benutzer bei einem Besuch auf der Internetseite bewegen. Dies hilft uns, die Funktionsweise unserer Internetseite zu verbessern, zum Beispiel indem gewährleistet wird, dass die Benutzer problemlos finden, wonach sie suchen. Weitere Informationen zu den einzelnen von uns genutzten Cookies und wofür wir sie verwenden finden Sie in der untenstehenden Tabelle:",
        cookie11: "Auch Cookies mit gezielter Werbung von Dritten werden bei Ihrem Besuch unserer Internetseite eingesetzt. Weitere Einzelheiten hierzu erfahren Sie unter dem Register Bannerwerbung",
        tableInfo29: "Trade Doubler",
        tableInfo30: "01716ca8622704ae607bb75720039166",
        tableInfo31: "Erkennt, dass der Besucher über eine Anzeige von Trade Doubler gekommen ist",
        tableInfo32: "Leistung",
        cookie12: "Sie blockieren Cookies, indem Sie in Ihrem Browser die Einstellung aktivieren, die es Ihnen erlaubt, das Setzen einzelner oder aller Cookies abzulehnen. Wenn Sie allerdings Ihre Browser-Einstellungen zum Blockieren aller Cookies (inklusive der grundlegenden Cookies) benutzen, sind eventuell nicht alle Bereiche unserer Internetseite für Sie zugänglich.",
        heading5: "VERWALTUNG DER COOKIES",
        cookie13: "Wenn Sie in Ihrem Browser keine Cookies aktiviert haben, bedeutet dies, dass das Einkaufserlebnis mit Ihrem Browser auf das Surfen und Recherchieren begrenzt ist, und Sie keine Waren kaufen können.",
        heading6: "Aktivierung von Cookies",
        cookie14: "Wenn Sie sich nicht sicher über die Art und Version des von Ihnen für das Internet verwendeten Webbrowsers sind:",
        boldText1: "AM PCs:",
        cookie15: "Klicken Sie oben in Ihrem Browserfenster auf ,,Hilfe'' und wählen Sie die Option „Über ...'' ",
        boldText2: "AM Macs:",
        cookie16: "Klicken Sie bei offenem Browserfenster auf das Apple-Menü und wählen Sie die Option ,,Über ...''",
        heading7: "Überprüfung der Aktivierung von Cookies an PCs",
        GoogleChrome: "Google Chrome",
        bullet1: "Klicken Sie oben in Ihrem Browserfenster auf das Werkzeug-Icon und anschließend auf Optionen",
        bullet2: "Klicken Sie auf das Register „Erweiterte Einstellungen”, suchen Sie den Abschnitt „Datenschutz” und klicken Sie auf die Schaltfläche „Inhaltseinstellungen”",
        bullet3: "Wählen Sie nun „Speicherung lokaler Daten zulassen”",
        IE: "Microsoft Internet Explorer 6.0, 7.0, 8.0",
        bullet4: "Klicken Sie oben im Browserfenster auf „Extras”, anschließend auf „Internetoptionen” und wählen Sie das Register „Datenschutz”",
        bullet5: "Vergewissern Sie sich, dass Ihre Datenschutzstufe auf „Mittel” oder geringer gestellt ist, sodass Cookies mit Ihrem Browser möglich sind",
        bullet6: "Höhere Einstellungen als „Mittel” deaktivieren Cookies",
        Mozilla: "Mozilla Firefox",
        bullet7: "Klicken Sie oben im Browserfenster auf „Extras” und wählen Sie „Einstellungen”",
        bullet8: "Klicken Sie dann auf das Datenschutz-Icon",
        bullet9: "Klicken Sie auf „Cookies” und wählen Sie anschließend „Cookies akzeptieren”",
        Safari: "Safari",
        bullet10: "Klicken Sie auf das Zahnradsymbol oben in Ihrem Browserfenster und wählen Sie die Option „Einstellungen”",
        bullet11: "Klicken Sie auf „Datenschutz” und prüfen Sie die Option „Cookies und andere Website-Daten unterdrücken: von Dritten oder Werbeanbietern”",
        bullet12: "Klicken Sie auf „Speichern”",
        Opera: "Opera",
        bullet13: "Klicken Sie oben in Ihrem Browserfenster auf „Menü” und wählen Sie „Einstellungen”",
        bullet14: "Anschließend wählen Sie das Register „Erweitert”",
        bullet15: "Wählen Sie dann die Option „Cookies annehmen”",
        SafariOsx: "Safari on OSX",
        bullet16: "Klicken Sie oben in Ihrem Browserfenster auf „Safari” und wählen Sie die Option „Einstellungen”",
        bullet17: "Klicken Sie auf „Sicherheit” und anschließend auf „Cookies akzeptieren”",
        bullet18: "Wählen Sie „Nur von Websites, die ich besuche”",
        heading8: "Alle anderen Browser",
        cookie17: "Bitte lesen Sie in Ihrer Dokumentation oder Ihrer Online-Hilfe nach.",
        heading9: "Weitere Informationen über Cookies",
        cookie18: "Wenn Sie mehr über Cookies im Allgemeinen und ihre Verwaltung erfahren möchten, besuchen Sie",
        link: "www.aboutcookies.org",
        cookie185: "(wird in einem neuen Fenster geöffnet – bitte beachten Sie, dass wir für den Inhalt externer Internetseiten nicht verantwortlich sind).",
        heading10: "BANNERWERBUNG AUF ANDEREN INTERNETSEITEN",
        cookie19: "Dieser Werbungstyp soll Ihnen auf der Grundlage der von Ihnen auf unserer Internetseite angesehenen Informationen eine Auswahl an Produkten bereitstellen, die Ihnen angezeigt werden, wenn Sie andere ausgewählte Internetseiten besuchen. Die Werbeanzeigen können Angebote hervorheben, die aufgrund Ihres Browserverlaufs als für Sie relevant eingestuft wurden. Die Technologie hinter einigen dieser Anzeigen beruht auf Cookies. Erfahren Sie mehr über Cookies und warum wir sie verwenden im Register „Was sind Cookies?”.",
        cookie20: null,
        heading11: "IHR DATENSCHUTZ",
        cookie21: "Sie können sicher sein, dass die in den Cookies enthaltenen Daten, die in diesen Anzeigen verwendet werden, vollständig anonym sind und keine persönlichen Daten beinhalten."
    },

    bp: {
        cookiesPolicy: "Política de cookies",
        heading1: "O QUE SÃO COOKIES?",
        cookie1: "Os cookies são pequenos ficheiros de texto guardados no seu computador sempre que visita determinadas páginas Web.Utilizamos os cookies para controlarmos o carro que está a reservar e para o reconhecermos quando regressar ao nosso site.",
        cookie2: "Para reservar um carro no nosso site web, necessita de ter os cookies activados - consulte a secção Gerir cookies.Se não pretender activar os cookies poderá ainda assim navegar no site e utilizá-lo para pesquisar.A maioria dos navegadores Web têm os cookies activados, mas verifique a secção Gerir cookies para obter ajuda na activação dos mesmos, caso necessite.",
        cookie3: "Note que os cookies não podem danificar o seu computador.Nos cookies que criamos não guardamos informações pessoalmente identificáveis, como por exemplo, informações do cartão de crédito, utilizamos informação encriptada reunida a partir dos cookies para ajudar a melhorar a experiência do utilizador no site. Por exemplo, ajudam-nos a identificar e resolver problemas.",
        cookie4: "Estamos a fornecer-lhe esta informação como parte da nossa iniciativa de estarmos em conformidade com a recente legislação e para garantirmos que somos honestos e transparentes no que se refere à sua privacidade quando está a utilizar o nosso site Web.",
        heading2: "A NOSSA POLÍTICA DE COOKIES",
        heading3: "INFORMAÇÃO SOBRE O NOSSO USO DE COOKIES",
        cookie5: "O nosso site Web utiliza cookies para distingui-lo de outros utilizadores que também o usam. Estes ajudam-nos a fornecer-lhe uma boa experiência quando navega no nosso site Web e também nos permite melhorar o nosso site.",
        cookie6: "Um cookie é um ficheiro pequeno de letras e números que, se aceitar, guardamos no seu navegador ou no disco rígido do seu computador. Os cookies contêm informação que é transferida para o disco rígido do seu computador.",
        cookie7: "Segue-se uma lista dos cookies principais que utilizamos e da respectiva finalidade.Encontrará informação sobre cookies de terceiros no próximo separador.",
        cookie8: "Com excepção dos cookies essenciais, todos os cookies expiram após 30 dias.",
        tableHeading1: "Nome do Cookie",
        tableHeading2: "Assemelha-se a",
        tableHeading3: "Objectivo do Cookie",
        tableHeading4: "Tipo",
        tableInfo1: "Cookie de Reserva",
        tableInfo2: "",
        tableInfo3: "Apresenta onde uma reserva foi efectuada",
        tableInfo4: "Estritamente Necessário",
        tableInfo5: "Chat Ao Vivo",
        tableInfo6: "__livechat, mp_ca50c6970591e306292637c2d7565daf_mixpanel __utmc, kvcd, __utma, km_uq, km_ai, km_lv LiveChat_13178052558062703",
        tableInfo7: "Permite aos utilizadores enviarem uma mensagem instantânea a um agente de serviço ao cliente",
        tableInfo8: "Funcional",
        tableInfo9: "Identificação do Cliente",
        tableInfo10: "clientCookie",
        tableInfo11: "Utilizado para manter o cliente correcto nas várias secções",
        tableInfo12: "Estritamente Necessário",
        tableInfo13: "Identificador de Sessão",
        tableInfo14: "7ktc6skvbat8dl0ddolggh5ij4",
        tableInfo15: "Identifica sessões entre sessões",
        tableInfo16: null,
        tableInfo17: "E-mail de abandono",
        tableInfo18: "email_id",
        tableInfo19: "Necessário para e-mail de abandono. Identifica quando os clientes visitam o site e saem sem efectuarem uma reserva.",
        tableInfo20: "Funcional",
        tableInfo21: "Omniture",
        tableInfo22: "s_vi, s_campaign, s_ppv, s_sq, s_cc",
        tableInfo23: "Omniture - significa rastreia para a omniture",
        tableInfo24: "Desempenho",
        tableInfo25: "Google Analytics",
        tableInfo26: "__utmz, __utmx, __utmxx, __utmc",
        tableInfo27: "Permite ao Google efectuar o rastreio no site Web",
        tableInfo28: "Desempenho",
        heading4: "COOKIES DE TERCEIROS",
        cookie9: "Quando visita o Cabforce poderá reparar em alguns cookies que não estão relacionados com a Cabforce. Quando visita uma página que contém conteúdo incorporado, por exemplo do YouTube, pode ficar sujeito ao envio de cookies por parte destes sites Web. Não controlamos a definição destes cookies, por isso sugerimos que verifique os sites Web de terceiros para obter mais informações sobre os cookies dos mesmos e sobre como os gerir..",
        cookie10: "Alguns dos cookies de terceiros que utilizamos são cookies 'analíticos'. Eles permitem-nos reconhecer e contar o número de visitantes e ver como estes se movimentam pelo site quando o estão a utilizar. Isto ajuda-nos a melhorar a forma como o site Web funciona, por exemplo, assegurando que os utilizadores encontram facilmente aquilo que procuram. Pode encontrar mais informações sobre os cookies individuais que utilizamos e as finalidades para os quais os utilizamos na tabela abaixo:.",
        cookie11: "Os cookies de terceiros relativamente a publicidade direcionada também são definidos quando visita o nosso site Web. Consulte o separador dos banners publicitários para mais informações",
        tableInfo29: "Trade Doubler",
        tableInfo30: "01716ca8622704ae607bb75720039166",
        tableInfo31: "dentifica os utilizadores como se tivessem chegado de em Anúncio do Trade Doubler",
        tableInfo32: "Desempenho",
        cookie12: "Bloqueia cookies activando a definição no seu browser que permite recusar a definição de todos ou de alguns cookies. Contudo se utilizar as definições do seu navegador para bloquear todos os cookies (incluindo cookies essenciais) poderá não conseguir aceder a todo ou a algumas secções do nosso site.",
        heading5: "GERIR COOKIES",
        cookie13: "Se não activou os cookies no seu navegador, significa que as compras no nosso navegador estarão limitadas a navegar e procurar, não poderá comprar itens.",
        heading6: "Activar cookies",
        cookie14: "Se tiver dúvidas acerca do tipo e da versão do navegador Web que utiliza para aceder à Internet:",
        boldText1: "Para PCs :",
        cookie15: "clique em 'Ajuda' na parte superior da janela do seu navegador e seleccione a opção 'Acerca do' ",
        boldText2: "Para Macs :",
        cookie16: "com a janela do navegador aberta, clique no menu da Apple e seleccione a opção 'Acerca do' ",
        heading7: "Como verificar se os cookies estão activados nos PCs",
        GoogleChrome: "Google Chrome (33.0.1750.146m)",
        bullet1: "Clique em 'Ferramentas' na parte superior da janela do seu navegador e, em seguida, clique em Opções",
        bullet2: "Clique no separador 'Definições Avançadas', localize a secção 'Privacidade' e clique no botão 'Definições de Conteúdo'",
        bullet3: "Seleccione agora 'Permitir definição dos dados locais (recomendado)'",
        IE: "Microsoft Internet Explorer (6.0, 7.0, 8.0)",
        bullet4: "Clique em 'Ferramentas' na parte superior da janela do seu navegador e clique em 'Opções da Internet' e, em seguida, clique no separador 'Privacidade'",
        bullet5: "Certifique-se de que o nível de Privacidade está definido para Médio ou inferior, o que permitirá activar cookies no seu navegador",
        bullet6: "As definições acima do Médio irão desactivar os cookies",
        Mozilla: "Mozilla Firefox (27.0.1)",
        bullet7: "Clique em 'Ferramentas' na parte superior da janela do seu navegador e seleccione Opções",
        bullet8: "Em seguida, clique no ícone Privacidade",
        bullet9: "Clique em Cookies e, em seguida, seleccione 'sites podem definir cookies'",
        Safari: "Safari (5.1)",
        bullet10: "Clique no ícone da engrenagem na parte superior da janela do seu navegador e seleccione a opção ''",
        bullet11: "Clique em 'Segurança', seleccione a opção 'Bloquear cookies de terceiros e anunciantes'",
        bullet12: "Clique em 'Guardar'|",
        Opera: "Opera (9.5.0)",
        bullet13: "Clique no 'Menu ' na parte superior da janela do seu navegador e seleccione 'Definições'",
        bullet14: "Em seguida, seleccione 'Preferências', seleccione o separador 'Avançadas'",
        bullet15: "Depois, seleccione a opção 'Aceitar cookies'",
        SafariOsx: "Safari no OSX (Lion)",
        bullet16: "Clique em 'Safari' na parte superior da janela do seu navegador e seleccione a opção 'Preferências'",
        bullet17: "Clique em 'Segurança' e depois em 'Aceitar cookies'",
        bullet18: "Seleccione 'Somente de sites que navega'",
        heading8: "Todos os outros navegadores",
        cookie17: "Verifique a sua documentação ou os seus ficheiros de ajuda on-line.",
        heading9: "Informação adicional sobre cookies",
        cookie18: "Se pretender obter mais informações sobre cookies em geral e sobre como geri-los, visite",
        link: "https://www.aboutcookies.org/",
        cookie185: "(abre-se numa janela nova - tenha em atenção que não podemos ser responsabilizados pelo conteúdo de sites Web externos).",
        heading10: "BANNERS PUBLICITÁRIOS NOUTROS SITES WEB",
        cookie19: "O objectivo deste tipo de publicidade é oferecer-lhe uma variedade de produtos com base naquilo que está a visualizar no nosso site Web, esse produtos são apresentados quando visita outros sites Webs seleccionados. Os anúncios podem destacar ofertas consideradas relevantes para o seu histórico de navegação. A tecnologia que suporta estes anúncios baseia-se nos cookies.",
        cookie20: "Saiba mais sobre cookies e porque os usamos através do separador 'O que são cookies'.",
        heading11: "A SUA PRIVACIDADE",
        cookie20: "Certifique-se de que os dados contidos nos cookies utilizados nestes anúncios são completamente anónimos e que não contêm quaisquer informações pessoais."
    }







})

// fr: {
    // cookiesPolicy: "",
    // heading1: "",
    // cookie1: "",
    // cookie2: "",
    // cookie3: "",
    // cookie4: "",
    // heading2: "",
    // heading3: "",
    // cookie5: "",
    // cookie6: "",
    // cookie7: "",
    // cookie8: "",
    // tableHeading1: "",
    // tableHeading2: "",
    // tableHeading3: "",
    // tableHeading4: "",
    // tableInfo1: "",
    // tableInfo2: "",
    // tableInfo3: "",
    // tableInfo4: "",
    // tableInfo5: "",
    // tableInfo6: "",
    // tableInfo7: "",
    // tableInfo8: "",
    // tableInfo9: "",
    // tableInfo10: "",
    // tableInfo11: "",
    // tableInfo12: "",
    // tableInfo13: "",
    // tableInfo14: "",
    // tableInfo15: "",
    // tableInfo16: null,
    // tableInfo17: "",
    // tableInfo18: "",
    // tableInfo19: "",
    // tableInfo20: "",
    // tableInfo21: "",
    // tableInfo22: "",
    // tableInfo23: "",
    // tableInfo24: "",
    // tableInfo25: "",
    // tableInfo26: "",
    // tableInfo27: "",
    // tableInfo28: "",
    // heading4: "",
    // cookie9: "",
    // cookie10: "",
    // cookie11: "",
    // tableInfo29: "",
    // tableInfo30: "",
    // tableInfo31: "",
    // tableInfo32: "",
    // cookie12: "",
    // heading5: "",
    // cookie13: "",
    // heading6: "",
    // cookie14: "",
    // boldText1: "",
    // cookie15: "",
    // boldText2: "",
    // cookie16: "",
    // heading7: "",
    // GoogleChrome: "",
    // bullet1: "",
    // bullet2: "",
    // bullet3: "",
    // IE: "",
    // bullet4: "",
    // bullet5: "",
    // bullet6: "",
    // Mozilla: "",
    // bullet7: "",
    // bullet8: "",
    // bullet9: "",
    // Safari: "",
    // bullet10: "",
    // bullet11: "",
    // bullet12: "",
    // Opera: "",
    // bullet13: "",
    // bullet14: "",
    // bullet15: "",
    // SafariOsx: "",
    // bullet16: "",
    // bullet17: "",
    // bullet18: "",
    // heading8: "",
    // cookie17: "",
    // heading9: "",
    // cookie18: "",
    // link: "",
    // cookie185: "",
    // heading10: "",
    // cookie19: "",
    // cookie20: "",
    // heading11: "",
    // cookie20: ""
// }